.IFNDEF	_MACROAPP__INCLUDED_
.EQU	_MACROAPP__INCLUDED_ = 1
.MESSAGE "Note: <macroapp.inc> have included, only once!" 
;=== BEGIN "macroapp.inc" ==================================================
; Прикладные Макроопределения, используемые при реализации логики приложения.
; (Примечание: эти макросы - "ПриложениеЗависимы"!)



;=== END "macroapp.inc" ====================================================
.ENDIF
